name: Build Geode Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/build-geode-mod/setup@main

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
